"""Volunteer

Revision ID: 1bd5b08b3d70
Revises: f780eced97b1
Create Date: 2024-10-17 17:01:41.707925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd5b08b3d70'
down_revision = 'f780eced97b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phoneNumber', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('lastLogin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lastLogin')
        batch_op.drop_column('phoneNumber')

    op.drop_table('communities')
    # ### end Alembic commands ###
